name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  GRADLE_USER_HOME: .gradle

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build natives with Gradle
        run: ./gradlew :gdx-box2d-box2d:jnigenBuild
      - name: Upload macOS/iOS natives
        uses: actions/upload-artifact@v2.1.4
        with:
          name: macos-natives
          path: gdx-box2d-box2d/libs

  linux:
    needs: macos
    runs-on: ubuntu-22.04
    env:
      ORG_GRADLE_PROJECT_GITHUB_USERNAME: ${{ github.actor }}
      ORG_GRADLE_PROJECT_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NDK_HOME: /usr/local/lib/android/sdk/ndk-bundle
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: sudo sed -i 's/deb http/deb [arch=amd64,i386] http/' /etc/apt/sources.list
      - run: sudo grep "ubuntu.com/ubuntu" /etc/apt/sources.list | sudo tee /etc/apt/sources.list.d/ports.list
      - run: sudo sed -i 's/amd64,i386/armhf,arm64/' /etc/apt/sources.list.d/ports.list
      - run: sudo sed -i 's#http://.*/ubuntu#http://ports.ubuntu.com/ubuntu-ports#' /etc/apt/sources.list.d/ports.list
      - name: Add extra platform architectures
        run: sudo dpkg --add-architecture i386; sudo dpkg --add-architecture armhf; sudo dpkg --add-architecture arm64
      - run: sudo apt-get update || true
      - name: Install Windows compilers
        run: sudo apt-get -yq install g++-mingw-w64-i686 g++-mingw-w64-x86-64
      - name: Install Linux x86 compilers/libraries
        run: sudo apt-get -yq install gcc-multilib g++-multilib linux-libc-dev-i386-cross libstdc++-12-dev-i386-cross
      - name: Install Linux arm32 compilers/libraries
        run: sudo apt-get -yq install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf binutils-arm-linux-gnueabihf
      - name: Install Linux arm64 compilers/libraries
        run: sudo apt-get -yq install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu
      - name: Download macOS/iOS natives
        uses: actions/download-artifact@v4.1.7
        with:
          name: macos-natives
          path: gdx-box2d-box2d/libs
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build natives with Gradle
        run: ./gradlew :gdx-box2d-box2d:jnigenBuild
      - name: Build Java with Gradle
        run: ./gradlew :gdx-box2d-box2d:assemble
      - name: Upload all output libs
        uses: actions/upload-artifact@v2.1.4
        with:
          name: output-libs
          path: |
            gdx-box2d-box2d/build/libs/
